$pdf_mode = 5;

$xelatex = "xelatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1 -shell-escape %O %S";
$xdvipdfmx = "xdvipdfmx -E -o %D %O %S";

$go_mode = 1;

$clean_ext = "los synctex.gz xdv";

$makeindex = "makeindex -s yaii.ist %O -o %D %S";
